# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QpluginWizard
                                 A QGIS plugin
 Wizard to evaluation assessment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-16
        git sha              : $Format:%H$
        copyright            : (C) 2025 by David Torres
        email                : davidt1987@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox

from .resources import *
from .project_database import ProjectDatabase
from .project_dock import ProjectDockWidget
from .plugin_wizard_dialog import QpluginWizardDialog


class QpluginWizard:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir, 'i18n', f'QpluginWizard_{locale}.qm'
        )
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Plugin Wizard')
        self.first_start = None

        # Project database (metadata only, no spatial data)
        db_path = os.path.join(self.plugin_dir, 'project.sqlite')
        self.project_db = ProjectDatabase(db_path)
        self.project_db.connect()

        # Dock widget — created once, shown/hidden on demand
        self._dock = None

    def tr(self, message):
        return QCoreApplication.translate('QpluginWizard', message)

    def add_action(self, icon_path, text, callback,
                   enabled_flag=True, add_to_menu=True, add_to_toolbar=True,
                   status_tip=None, whats_this=None, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        if status_tip:
            action.setStatusTip(status_tip)
        if whats_this:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/plugin_wizard/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Wizard'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Plugin Wizard'), action)
            self.iface.removeToolBarIcon(action)

        if self._dock is not None:
            self.iface.mainWindow().removeDockWidget(self._dock)
            self._dock.deleteLater()
            self._dock = None

        self.project_db.disconnect()

    # ------------------------------------------------------------------
    # Run — show the project dock
    # ------------------------------------------------------------------

    def run(self):
        """Show the Project dock panel."""
        if self._dock is None:
            self._dock = ProjectDockWidget(
                self.iface, self.project_db,
                parent=self.iface.mainWindow()
            )
            self._dock.launch_wizard.connect(self._open_wizard)
            self.iface.mainWindow().addDockWidget(Qt.RightDockWidgetArea, self._dock)

        self._dock.show()
        self._dock.raise_()

    # ------------------------------------------------------------------
    # Wizard launch
    # ------------------------------------------------------------------

    def _open_wizard(self, project_id, project_name):
        """Open the Plugin Wizard for the selected project."""
        try:
            dlg = QpluginWizardDialog(
                iface=self.iface,
                project_id=project_id,
                project_name=project_name,
                project_db=self.project_db
            )
            dlg.exec_()
            # Refresh the dock tree after the wizard closes (new assessment may exist)
            if self._dock is not None:
                self._dock.refresh()
        except Exception as e:
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Wizard Error",
                f"Failed to open Plugin Wizard:\n{str(e)}"
            )
